apiVersion: v1
kind: Secret
metadata:
  name: diracx-secrets
stringData:
{{ .Values.diracx.settings | toYaml | indent 2 }}
{{- if and .Values.developer.enabled .Values.mysql.enabled }}
  {{- range $dbName := .Values.diracx.mysqlDatabases }}
  DIRACX_DB_URL_{{ $dbName | upper }}: "mysql+aiomysql://{{ $.Values.mysql.auth.username }}:{{ $.Values.mysql.auth.password }}@{{ $.Release.Name }}-mysql:3306/{{ $dbName }}"
  {{- end }}
{{- end }}
---
{{- if .Values.diracx.manageSQLSchema }}
apiVersion: v1
kind: Secret
metadata:
  name: diracx-init-mysql-secrets
stringData:
{{- if and .Values.developer.enabled .Values.mysql.enabled }}
  {{- range $dbName := .Values.diracx.mysqlDatabases }}
  DIRACX_DB_URL_{{ $dbName | upper }}: "mysql+aiomysql://root:{{ $.Values.mysql.auth.rootPassword }}@{{ $.Release.Name }}-mysql:3306/{{ $dbName }}"
  {{- end }}
{{- end }}
{{- end }}
